name: 'PagerDuty Alert'
description: 'GitHub Action to send a PagerDuty alert, e.g. on action failure.'
inputs:
  pagerduty-integration-key:
    description: 'The integration key for your PagerDuty service'
    required: true
  pagerduty-dedup-key:
    description: 'The key used to correlate PagerDuty triggers, acknowledges, and resolves for the same alert.'
    required: false
  pagerduty-alert-severity:
    description: 'The severity level used when creating a PagerDuty event'
    required: false
    default: critical
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'alert-triangle'
  color: 'red'
